// client/src/routes/Root/Root.tsx
import { Link, NavLink, Outlet } from "react-router-dom"
import AccountCircle from "@mui/icons-material/AccountCircle"
import "./styles.css"
import { UserProvider, useUserContext } from "./context"
import {
  AppBar,
  Button,
  Menu,
  MenuItem,
  Stack,
  Toolbar,
  Typography,
} from "@mui/material"
import { useState } from "react"

export const Root = () => {
  return (
    <UserProvider>
      <MainHeader />
      <main>
        <Outlet />
      </main>
    </UserProvider>
  )
}

const MainHeader = () => {
  const { username } = useUserContext()
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null)
  const handleMenu = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget)
  }

  const handleClose = () => {
    setAnchorEl(null)
  }
  return (
    <AppBar position="static">
      <Toolbar>
        <Stack direction="row" spacing={2}>
          <Button variant="text" color="inherit" component={NavLink} to="/">
            Home
          </Button>
          <Button
            variant="text"
            color="inherit"
            component={NavLink}
            to="/games"
          >
            Games
          </Button>
        </Stack>
        <div style={{ marginLeft: "auto" }}>
          <Button
            size="small"
            aria-label="account of current user"
            aria-controls="menu-appbar"
            aria-haspopup="true"
            onClick={handleMenu}
            color="inherit"
          >
            <AccountCircle />
            <Typography variant="h6">{username}</Typography>
          </Button>
          <Menu
            id="menu-appbar"
            anchorEl={anchorEl}
            anchorOrigin={{
              vertical: "top",
              horizontal: "right",
            }}
            keepMounted
            transformOrigin={{
              vertical: "top",
              horizontal: "right",
            }}
            open={Boolean(anchorEl)}
            onClose={handleClose}
          >
            <MenuItem onClick={handleClose} component={Link} to="/profile">
              Profile
            </MenuItem>
            <MenuItem onClick={handleClose} component={Link} to="/logout">
              Logout
            </MenuItem>
          </Menu>
        </div>
      </Toolbar>
    </AppBar>
  )
}

// solidjs-client/src/routes/Root/Root.tsx
import "./styles.css"
import { createSignal, JSXElement } from "solid-js"
import { UserProvider, useUserContext } from "./context"
import {
  AppBar,
  Button,
  Menu,
  MenuItem,
  Stack,
  Toolbar,
  Typography,
} from "@suid/material"
import AccountCircle from "@suid/icons-material/AccountCircle"
import { A } from "@solidjs/router"

const Root = (props: { children?: JSXElement }) => {
  return (
    <UserProvider>
      <MainHeader />
      <main>{props.children}</main>
    </UserProvider>
  )
}

export default Root

const MainHeader = () => {
  const user = useUserContext()

  const [anchorEl, setAnchorEl] = createSignal<null | HTMLElement>(null)
  const open = () => Boolean(anchorEl())
  const handleMenu = (event: { currentTarget: HTMLButtonElement }) => {
    setAnchorEl(event.currentTarget)
  }

  const handleClose = () => {
    setAnchorEl(null)
  }
  return (
    <AppBar position="static">
      <Toolbar>
        <Stack direction="row" spacing={2}>
          <Button variant="text" color="inherit" component={A} href="/">
            Home
          </Button>
          <Button variant="text" color="inherit" component={A} href="/games">
            Games
          </Button>
        </Stack>
        <div style={{ "margin-left": "auto" }}>
          <Button
            size="small"
            aria-label="account of current user"
            aria-controls="menu-appbar"
            aria-haspopup="true"
            onClick={handleMenu}
            color="inherit"
          >
            <AccountCircle />
            <Typography variant="h6">{user.username}</Typography>
          </Button>
          <Menu
            id="menu-appbar"
            anchorEl={anchorEl()}
            anchorOrigin={{
              vertical: "top",
              horizontal: "right",
            }}
            transformOrigin={{
              vertical: "top",
              horizontal: "right",
            }}
            open={open()}
            onClose={handleClose}
          >
            <MenuItem onClick={handleClose} component={A} href="/profile">
              Profile
            </MenuItem>
            <MenuItem onClick={handleClose} component={A} href="/logout">
              Logout
            </MenuItem>
          </Menu>
        </div>
      </Toolbar>
    </AppBar>
  )
}
