// client/src/main.tsx
import React from "react"
import ReactDOM from "react-dom/client"
import "./styles.css"
import { RouterProvider, createBrowserRouter } from "react-router-dom"
import { RootRoute } from "./routes/Root/route"
import { IndexRoute } from "./routes/index/route"
import "@fontsource/roboto/300.css"
import "@fontsource/roboto/400.css"
import "@fontsource/roboto/500.css"
import "@fontsource/roboto/700.css"
import { LoginRoute } from "./routes/login/route"
import { SignupRoute } from "./routes/signup/route"
import { GamesIdRoute } from "./routes/_games.$gameId/route"
import { LogoutRoute } from "./routes/logout/route"
import { ThemeProvider } from "@emotion/react"
import { createTheme } from "@mui/material"
import { GamesRoute } from "./routes/games/route"
import { GameReviewRoute } from "./routes/_games._$gameId.review/route"
import { DatasourceProvider } from "./datasources/datasource-provider"
import { GamesJoinRoute } from "./routes/_games.join/route"

const theme = createTheme({
  palette: {
    primary: {
      main: "#4e7837",
    },
    secondary: {
      main: "#4b4847",
    },
  },
})

const rootElement = document.getElementById("root")

if (!rootElement) {
  throw new Error("No root element found")
}

const router = createBrowserRouter([
  RootRoute([
    GamesIdRoute(),
    GamesJoinRoute(),
    GamesRoute(),
    GameReviewRoute(),
    IndexRoute(),
  ]),
  LoginRoute(),
  SignupRoute(),
  LogoutRoute(),
])

ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <ThemeProvider theme={theme}>
      <DatasourceProvider>
        <RouterProvider router={router} />
      </DatasourceProvider>
    </ThemeProvider>
  </React.StrictMode>,
)

// solidjs-client/src/index.tsx
import { render } from "solid-js/web"
import { Router } from "@solidjs/router"
import { RootRoute } from "./routes/Root/route"
import { DatasourceProvider } from "./datasources/datasource-provider"
import { LoginRoute } from "./routes/login/route"
import "./index.css"
import { SignupRoute } from "./routes/signup/route"
import { createTheme, ThemeProvider } from "@suid/material"
import { GamesRoute } from "./routes/games/route"
import { GamesJoinRoute } from "./routes/_games.join/route"
import { LogoutRoute } from "./routes/logout/route"
import { GameReviewRoute } from "./routes/_games._$gameId.review/route"
import { GamesIdRoute } from "./routes/_games.$gameId/route"

const wrapper = document.getElementById("root")

if (!wrapper) {
  throw new Error("Wrapper div not found")
}

const routes = [
  RootRoute([
    GamesRoute(),
    GamesJoinRoute(),
    GameReviewRoute(),
    GamesIdRoute(),
  ]),
  LoginRoute(),
  LogoutRoute(),
  SignupRoute(),
]

const theme = createTheme({
  palette: {
    primary: {
      main: "#4e7837",
    },
    secondary: {
      main: "#4b4847",
    },
  },
})

render(
  () => (
    <DatasourceProvider>
      <ThemeProvider theme={theme}>
        <Router>{routes}</Router>
      </ThemeProvider>
    </DatasourceProvider>
  ),
  wrapper,
)
