// solidjs-client/src/routes/_games.$gameId/components/board.tsx
import { useGameContext } from "../context/useContext"
import { GameOverDialog } from "../components/game-over-dialog"
import { GameBoard } from "../../../components/GameBoard"
import { Key } from "chessground/types"
import { Show } from "solid-js"
import { Stack } from "@/ui"

export const Board = () => {
  const gameContext = useGameContext()

  function onDrop(orig: Key, dest: Key) {
    const move = {
      from: orig,
      to: dest,
      // promotion: "Q",
    }
    const result = gameContext().onMove(move)
    return result !== null
  }

  return (
    <Show when={gameContext().fen} fallback={<div>Loading...</div>}>
      <Stack
        direction="column"
        alignItems="center"
        justifyContent="center"
        style={{
          display: "flex",
          height: "calc(100vh - 96px)",
          "max-height": "100vw",
          width: "100%",
          "max-width": "800px",
          "box-sizing": "border-box",
        }}
      >
        <GameOverDialog />
        <pre>{gameContext().fen}</pre>
        <GameBoard
          fen={gameContext().fen!}
          whitePlayer={gameContext().whitePlayer}
          blackPlayer={gameContext().blackPlayer}
          myColor={gameContext().myColor}
          onPieceDrop={onDrop}
        />
      </Stack>
    </Show>
  )
}

// client/src/routes/_games.$gameId/components/board.tsx
import { Square } from "chess.js"
import { useGameContext } from "../context/useContext"
import { GameOverDialog } from "../components/game-over-dialog"
import { Piece } from "react-chessboard/dist/chessboard/types"
import { GameBoard } from "../../../components/GameBoard"

export const Board = () => {
  const { fen, onMove, myColor, whitePlayer, blackPlayer } = useGameContext()

  function onDrop(sourceSquare: Square, targetSquare: Square, piece: Piece) {
    const promotion = piece.toLowerCase()[1]
    const move = {
      from: sourceSquare,
      to: targetSquare,
      promotion,
    }
    const result = onMove(move)
    return result !== null
  }

  return fen ? (
    <div style={{ width: 800, height: 800 }}>
      <GameOverDialog />
      <GameBoard
        fen={fen}
        whitePlayer={whitePlayer}
        blackPlayer={blackPlayer}
        myColor={myColor}
        onPieceDrop={onDrop}
      />
    </div>
  ) : (
    <div>Loading... </div>
  )
}
