// solidjs-client/src/routes/signup/Signup.tsx
import { useNavigate } from "@solidjs/router"
import { storeToken } from "../../lib/token"
import {
  Button,
  Link,
  Paper,
  Stack,
  TextField,
  Typography,
} from "../../common-ui"
import { useSignupWithReactQuery } from "./data/react-query/useSignupWithReactQuery"

export const Signup = () => {
  const navigate = useNavigate()

  const paperStyle = {
    padding: "20px",
    "max-width": "300px",
  }
  const btnstyle = { margin: "8px 0" }

  const signupHandlers = useSignupWithReactQuery()

  console.log({ signupHandlers })
  const onSubmit = (e: SubmitEvent) => {
    e.preventDefault()

    console.log({ inthefunction: signupHandlers })
    const form = e.currentTarget as HTMLFormElement
    const formData = new FormData(form)
    const username = formData.get("username") as string
    const password = formData.get("password") as string

    signupHandlers.mutate(
      { username, password },
      {
        onSuccess: (data) => {
          storeToken(data.token)
          navigate("/dashboard")
        },
      },
    )
    // signupHandlers.mutate({ username, password }), (token) => {
    //   storeToken(token)
    //   navigate("/dashboard")
    // })
  }

  return (
    <div
      style={{
        display: "flex",
        "justify-content": "center",
        "align-items": "center",
        "min-height": "100vh",
        "min-width": "100vw",
      }}
    >
      <Paper elevation={10} style={paperStyle}>
        <form onSubmit={onSubmit}>
          <Stack direction="column" spacing={3}>
            <Typography align="center" variant="h3">
              Sign Up
            </Typography>
            {signupHandlers.isError && (
              <Typography variant="subtitle2" color="error">
                {signupHandlers.error.message}
              </Typography>
            )}
            <TextField
              label="Username"
              placeholder="Enter username"
              variant="outlined"
              fullWidth
              required
              autoComplete="username"
              name="username"
            />
            <TextField
              label="Password"
              placeholder="Enter password"
              type="password"
              variant="outlined"
              autoComplete="current-password"
              fullWidth
              required
              name="password"
            />

            <Button
              variant="primary"
              type="submit"
              style={btnstyle}
              fullWidth
              disabled={signupHandlers.isPending}
            >
              Register
            </Button>
            <Typography>
              Already have an account? <Link href="/login">Sign In</Link>
            </Typography>
          </Stack>
        </form>
      </Paper>
    </div>
  )
}

// vue-client/src/pages/signup.vue
<template>
  <div
    style="
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      min-width: 100vw;
    "
  >
    <v-sheet elevation="10" max-width="300" style="padding: 20px" rounded="lg">
      <form @submit="onSubmit">
        <div style="display: flex; flex-direction: column; gap: 8px">
          <div class="text-h3" align="center">Sign Up</div>
          <div v-if="error" class="text-red" align="center">{{ error }}</div>
          <v-text-field
            v-model="username"
            label="Username"
            placeholder="Enter username"
            variant="outlined"
            fullWidth
            required
            autocomplete="username"
            name="username"
          ></v-text-field>
          <v-text-field
            v-model="password"
            label="Password"
            placeholder="Enter password"
            type="password"
            variant="outlined"
            autocomplete="current-password"
            fullWidth
            required
            name="password"
          ></v-text-field>
          <v-btn color="primary" width="100%" type="submit"> Register </v-btn>
          <div>
            Already have an account?
            <router-link to="/login" class="text-primary">Sign in</router-link>
          </div>
        </div>
      </form>
    </v-sheet>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue"
import { useRegisterMutation } from "@/datasources/operations/mutations/signup.operation"
import { storeToken } from "@/lib/token"
import router from "@/router"

export default defineComponent({
  setup() {
    const username = ref("")
    const password = ref("")
    const error = ref("")

    const { mutate, onDone } = useRegisterMutation()
    const onSubmit = (e: Event) => {
      e.preventDefault()
      mutate({ username: username.value, password: password.value })
      onDone((result) => {
        const data = result.data
        if (!data) return
        if (data.register.__typename === "RegisterSuccess") {
          storeToken(data.register.token)
          router.push("/dashboard")
          return
        }

        if (data.register.__typename === "RegisterError") {
          error.value =
            data.register.message === "USER_ALREADY_EXISTS"
              ? "User already exists"
              : "Unknown server error"
        }
      })
    }

    return { username, password, error, onSubmit }
  },
})
</script>
