// client/src/lib/react-query.tsx
import {
  QueryClient,
  QueryClientProvider as ReactQueryClientProvider,
} from "@tanstack/react-query"

const queryClient = new QueryClient()

export const QueryClientProvier = (props: { children: React.ReactNode }) => {
  return (
    <ReactQueryClientProvider client={queryClient}>
      {props.children}
    </ReactQueryClientProvider>
  )
}

// solidjs-client/src/datasources/solid-query.tsx
import {
  QueryClient,
  QueryClientProvider as SolidQueryProvider,
} from "@tanstack/solid-query"
import { JSX } from "solid-js"

const queryClient = new QueryClient()

export const QueryClientProvier = (props: { children: JSX.Element }) => {
  return (
    <SolidQueryProvider client={queryClient}>
      {props.children}
    </SolidQueryProvider>
  )
}
